apiVersion: "greenplum.pivotal.io/v1"
kind: "GreenplumCluster"
metadata:
  name: greenplum
spec:
  masterAndStandby:
    hostBasedAuthentication: |
      host   all   all   0.0.0.0/0   trust
      host   all   all   ::0/0       trust
    memory: "800Mi"
    cpu: "0.5"
    storageClassName: standard
    storage: 1000G
    workerSelector: {}
  segments:
    primarySegmentCount: 5
    memory: "2Gi"
    cpu: "0.5"
    storageClassName: managed-nfs-storage
    storage: 2000G
    workerSelector: {}
  pl:
    serviceName: "greenplum-pl"
  pxf:
    serviceName: "greenplum-pxf"
  gptext:
    serviceName: "greenplum-gptext"

---
apiVersion: "greenplum.pivotal.io/v1beta1"
kind: "GreenplumPLService"
metadata:
  name: greenplum-pl
spec:
  replicas: 3
  cpu: "0.8"
  memory: "4Gi"
  workerSelector: {}

---
apiVersion: "greenplum.pivotal.io/v1beta1"
kind: "GreenplumPXFService"
metadata:
  name: greenplum-pxf
spec:
  replicas: 2
  cpu: "0.5"
  memory: "1Gi"
  workerSelector: {}
#  pxfConf:
#    s3Source:
#      secret: "greenplum-pxf-configs"
#      endpoint: "s3.amazonaws.com"
#      bucket: "YOUR_S3_BUCKET_NAME"
#      folder: "YOUR_S3_BUCKET_FOLDER-Optional"
#
# Note: If using pxfConf.s3Source, in addition to applying the above yaml be sure to create a secret using a command similar to:
# kubectl create secret generic greenplum-pxf-configs --from-literal='access_key_id=XXX' --from-literal='secret_access_key=XXX'

---
apiVersion: "greenplum.pivotal.io/v1beta1"
kind: "GreenplumTextService"
metadata:
  name: greenplum-gptext
spec:
  solr:
    replicas: 2
    cpu: "0.5"
    memory: "1Gi"
    workerSelector: {}
    storageClassName: standard
    storage: 100M
  zookeeper:
    replicas: 3
    cpu: "0.5"
    memory: "1Gi"
    workerSelector: {}
    storageClassName: standard
    storage: 100M
